### ISSUE TITLE
Proposal for MainMenu

### ISSUE THREAD

**Issue by johanlef** [LEFapps/admindashboard#2]
```DIFF
const paths = [
  {
    path: '/articles',
    component: Articles,
    label: 'Articles'
  },
  {
    path: '/comments',
    component: Comments,
    label: 'Comments',
+   excludeFromMenu: true
  }
]
```
Menu in eerste _Board_ wordt opgebouwd obv `paths`, ineens met juiste classes en bijhorende css.

`children` in de basiscomponent `AdminDashboard` is dan niet langer de inhoud van het eerste paneel, maar inhoud in het lege vak rechts. Bijvoorbeeld:
- meest recente _articles_
- tien laatste _comments_
- _notifications_ van de huidige _user_
- laatste _logs_
… of een combinatie natuurlijk.

@TomasVink Wat denk je?

**Comment by TomasVink** [comment]
Akkoord, go for it! Had het nu ook al zo in de GSDT gedaan voor het eerste menu en was inderdaad wat aan het twijfelen of dat niet gewoon standaard in de dashboard zou moeten zitten.
